//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accruals
    {
        public Accruals()
        {
            this.Meter_reading = new HashSet<Meter_reading>();
            this.User = new HashSet<User>();
        }
    
        public int ID_Начисления { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual ICollection<Meter_reading> Meter_reading { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
