//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard1
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.Сounter = new HashSet<Сounter>();
        }
    
        public int ID_Дома { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
    
        public virtual ICollection<Сounter> Сounter { get; set; }
    }
}
