//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meter_reading
    {
        public int ID_Показания_счетчика { get; set; }
        public Nullable<int> ID_Тариф { get; set; }
        public Nullable<int> ID_Счетчика { get; set; }
        public string Значение { get; set; }
        public Nullable<int> ID_Начисления { get; set; }
        public string Сумма_начисления { get; set; }
        public Nullable<System.DateTime> Дата_отправки { get; set; }
        public Nullable<long> Отправлено { get; set; }
        public Nullable<System.DateTime> Дата_регистрации { get; set; }
        public string Расход { get; set; }
        public Nullable<bool> Данные_загружены { get; set; }
    
        public virtual Accruals Accruals { get; set; }
        public virtual Rate Rate { get; set; }
        public virtual Сounter Сounter { get; set; }
    }
}
