//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public Rate()
        {
            this.Meter_reading = new HashSet<Meter_reading>();
        }
    
        public int ID_Тариф { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> ID_Тип_ресурса { get; set; }
        public string Значение { get; set; }
        public Nullable<bool> Действущий { get; set; }
    
        public virtual ICollection<Meter_reading> Meter_reading { get; set; }
    }
}
