//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_type
    {
        public Resource_type()
        {
            this.Сounter = new HashSet<Сounter>();
        }
    
        public int ID_Тип_ресурса { get; set; }
        public string Название { get; set; }
        public string Единица_измерения { get; set; }
    
        public virtual ICollection<Сounter> Сounter { get; set; }
    }
}
