//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_type
    {
        public User_type()
        {
            this.User = new HashSet<User>();
        }
    
        public int ID_Тип_пользователя { get; set; }
        public string Название { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
