//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID_Пользователь { get; set; }
        public string Login { get; set; }
        public string Passowrd { get; set; }
        public Nullable<int> ID_Тип_пользователя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public Nullable<int> ID_Текущее_начисление { get; set; }
    
        public virtual Accruals Accruals { get; set; }
        public virtual User_type User_type { get; set; }
    }
}
