//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сounter
    {
        public Сounter()
        {
            this.Meter_reading = new HashSet<Meter_reading>();
        }
    
        public int ID_Счетчик { get; set; }
        public Nullable<System.DateTime> Дата_регистрации { get; set; }
        public Nullable<int> Значение { get; set; }
        public Nullable<System.DateTime> Дата_списания { get; set; }
        public Nullable<int> Номер { get; set; }
        public Nullable<int> ID_Клиента { get; set; }
        public Nullable<int> ID_Тип_ресурса { get; set; }
        public Nullable<bool> Действущий { get; set; }
        public Nullable<int> ID_Дома { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual House House { get; set; }
        public virtual ICollection<Meter_reading> Meter_reading { get; set; }
        public virtual Resource_type Resource_type { get; set; }
    }
}
